branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "node scripts/update_pubspec_version.js ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets:
        - "pubspec.yaml"
        - "CHANGELOG.md"
      message: "chore: release ${nextRelease.version} [skip ci]"