name: Auto Version
on:
  push:
    branches: [main]

jobs:
  auto_version:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use PAT instead of GITHUB_TOKEN
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          persist-credentials: true

      - name: Configure Git with PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Configure git to use the PAT for authentication
          git config url."https://x-access-token:${{ secrets.SEMANTIC_RELEASE_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify setup
        run: |
          echo "Checking git configuration..."
          git config --list | grep user

          echo "Checking branch protection status..."
          echo "Current branch: $(git branch --show-current)"

          echo "Checking script permissions..."
          ls -la scripts/

          echo "Testing script..."
          node scripts/update_pubspec_version.js 0.0.1-test
          git checkout pubspec.yaml  # Reset test change

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: |
          echo "Running semantic-release..."
          npx semantic-release
